local Localisation = {}

local Structures = require("Union.UnionStructures")

local LocalisationKey = {
    En = {
        presence_menu_offline   = "Idling in the Main Menu",
        presence_menu_online    = "Idling in an Online Lobby",
        presence_inmenus        = "In Menus",
        presence_jukebox        = "Layin’ the Wax and Spinnin' the sound!",
        presence_courseselect   = "Selecting a Course",
        presence_prixselect     = "Selecting a Grand Prix",
        presence_class          = "Selecting a Speed Class",
        presence_racerselect    = "Selecting a Character & Machine",
        presence_friendmatch    = "Friend Match",
        presence_paused         = "Game Paused",
        presence_garage         = "Customizing a Machine",
        presence_finish         = "Race Finished",
        presence_uniondiscord   = "UnionDiscord %s",
        presence_mainmenu       = "Main Menu",
        presence_grandprix      = "Grand Prix",
        presence_timetrial      = "Time Trial",
        presence_partyrace      = "Race Park",
        presence_rankmatch      = "World Match",
        presence_fest           = "Festival",
        presence_legend         = "Legend Competition",
        presence_wait           = "Waiting",
        presence_racing         = "%s at %s",
        presence_car            = "Racing",
        presence_boat           = "Boating",
        presence_plane          = "Flying",
        presence_racingranked   = "Competing at %s Rank",
        presence_normalspeed    = "a Normal Speed",
        presence_highspeed      = "High Speed",
        presence_sonicspeed      = "Sonic Speed",
        presence_supersonicspeed = "Super Sonic Speed!",
        presence_lap             = "Lap %s/3",
        presence_1st             = "1st",
        presence_2nd             = "2nd",
        presence_3rd             = "3rd",
        presence_4th             = "4th",
        presence_5th             = "5th",
        presence_6th             = "6th",
        presence_7th             = "7th",
        presence_8th             = "8th",
        presence_9th             = "9th",
        presence_10th            = "10th",
        presence_11th            = "11th",
        presence_12th            = "12th",
    },

    -- Machine Translation: (28-09-2025)
    Ja = {
        presence_menu_offline    = "メインメニューで待機中",
        presence_menu_online     = "オンラインロビーで待機中",
        presence_inmenus         = "メニュー中",
        presence_jukebox         = "レコードを回して音楽を再生中！",
        presence_courseselect    = "コースを選択中",
        presence_prixselect      = "グランプリを選択中",
        presence_class           = "速度クラスを選択中",
        presence_racerselect     = "キャラクター＆マシンを選択中",
        presence_friendmatch     = "フレンドマッチ",
        presence_paused          = "ゲーム一時停止",
        presence_garage          = "マシンをカスタマイズ中",
        presence_finish          = "レース終了",
        presence_uniondiscord    = "UNIONDISCORD %s",
        presence_mainmenu        = "メインメニュー",
        presence_grandprix       = "グランプリ",
        presence_timetrial       = "タイムトライアル",
        presence_partyrace       = "レースパーク",
        presence_rankmatch       = "ワールドマッチ",
        presence_fest            = "フェスティバル",
        presence_legend          = "レジェンド競技",
        presence_wait            = "待機中",
        presence_racing          = "%sでレース中",
        presence_racingranked    = "%sで競技中",
        presence_normalspeed     = "ノーマルスピード",
        presence_highspeed       = "ハイスピード",
        presence_sonicspeed      = "ソニックスピード",
        presence_supersonicspeed = "スーパートニックスピード！",
        presence_lap             = "周回 %s/3",
        presence_1st             = "1st",
        presence_2nd             = "2nd",
        presence_3rd             = "3rd",
        presence_4th             = "4th",
        presence_5th             = "5th",
        presence_6th             = "6th",
        presence_7th             = "7th",
        presence_8th             = "8th",
        presence_9th             = "9th",
        presence_10th            = "10th",
        presence_11th            = "11th",
        presence_12th            = "12th",
    },
    

    -- Updated Translation for 0.2 release: red1fouad (05-10-2025)
    Fr = {
        presence_menu_offline    = "Inactif dans le menu principal",
        presence_menu_online     = "Inactif dans un salon en ligne",
        presence_inmenus         = "Dans les menus",
        presence_jukebox         = "Pose le vinyle et fait tourner le son !",
        presence_courseselect    = "Sélection d’un circuit",
        presence_prixselect      = "Sélection d’un Grand Prix",
        presence_class           = "Sélection d’une classe de vitesse",
        presence_racerselect     = "Sélection d’un personnage et d’une machine",
        presence_friendmatch     = "Partie entre amis",
        presence_paused          = "Jeu en pause",
        presence_garage          = "Personnalisation d’une machine",
        presence_finish          = "Course terminée",
        presence_uniondiscord    = "UnionDiscord %s",
        presence_mainmenu        = "Menu principal",
        presence_grandprix       = "Grand Prix",
        presence_timetrial       = "Contre-la-montre",
        presence_partyrace       = "Parc de course",
        presence_rankmatch       = "Match mondial",
        presence_fest            = "Festival",
        presence_legend          = "Compétition légendaire",
        presence_wait            = "En attente",
        presence_racing          = "%s à %s",
        presence_car             = "Conduisant",
        presence_boat            = "Naviguant",
        presence_plane           = "Volant",
        presence_racingranked    = "Compétition à %s rang",
        presence_normalspeed     = "à vitesse normale",
        presence_highspeed       = "à haute vitesse",
        presence_sonicspeed      = "à vitesse sonique",
        presence_supersonicspeed = "à vitesse supersonique !",
        presence_lap             = "Tour %s/3",
        presence_1st             = "1er",
        presence_2nd             = "2e",
        presence_3rd             = "3e",
        presence_4th             = "4e",
        presence_5th             = "5e",
        presence_6th             = "6e",
        presence_7th             = "7e",
        presence_8th             = "8e",
        presence_9th             = "9e",
        presence_10th            = "10e",
        presence_11th            = "11e",
        presence_12th            = "12e",
    },

    -- Translated by: ema.idk.something (02-10-2025)
    It = {
        presence_menu_offline    = "Si rilassa nel Menu Principale",
        presence_menu_online     = "È in attesa in una Lobby Online",
        presence_inmenus         = "Nei menu",
        presence_jukebox         = "Danzando al ritmo della musica!",
        presence_courseselect    = "Scegliendo un Tracciato",
        presence_prixselect      = "Scegliendo una Coppa",
        presence_class           = "Scegliendo una Velocità",
        presence_racerselect     = "Scegliendo un Personaggio e un Veicolo",
        presence_friendmatch     = "Partita Amichevole",
        presence_paused          = "Gioco in pausa",
        presence_garage          = "Personalizzando un Veicolo",
        presence_finish          = "Fine gara",
        presence_uniondiscord    = "UnionDiscord %s",
        presence_mainmenu        = "Menu Principale",
        presence_grandprix       = "Gran Premio",
        presence_timetrial       = "Prova a tempo",
        presence_partyrace       = "Parco Delle Corse",
        presence_rankmatch       = "Partita Mondiale",
        presence_fest            = "In una partita Festival",
        presence_legend          = "Competizione tra leggende",
        presence_wait            = "In attesa",
        presence_racing          = "%s a %s",
        presence_car             = "Gareggiando",
        presence_boat            = "Nuotando",
        presence_plane           = "Volando",
        presence_racingranked    = "Compete in %s",
        presence_normalspeed     = "Velocità Normale",
        presence_highspeed       = "Velocità Alta",
        presence_sonicspeed      = "Velocità Sonica!",
        presence_supersonicspeed = "Velocità Super Sonica!!!",
        presence_lap             = "Giro %s/3",
        presence_1st             = "1°",
        presence_2nd             = "2°",
        presence_3rd             = "3°",
        presence_4th             = "4°",
        presence_5th             = "5°",
        presence_6th             = "6°",
        presence_7th             = "7°",
        presence_8th             = "8°",
        presence_9th             = "9°",
        presence_10th            = "10°",
        presence_11th            = "11°",
        presence_12th            = "12°",
    },

    -- Translated by: a5tronomy (27-09-2025) and sechscomic73130 (02-10-2025)
    De = {
        presence_menu_offline    = "Im Hauptmenü",
        presence_menu_online     = "In Online-Lobby",
        presence_inmenus         = "In Menüs",
        presence_jukebox         = "Hört Musik im Jukebox-Modus",
        presence_courseselect    = "Wählt Strecke",
        presence_grandprix       = "Wählt Grand Prix",
        presence_class           = "Wählt Geschwindigkeitsklasse",
        presence_racerselect     = "Wählt Charakter und Maschine",
        presence_friendmatch     = "Freundschaftsspiel",
        presence_paused          = "Pausiert",
        presence_garage          = "Passt Maschine an",
        presence_finish          = "Rennen abgeschlossen",
        presence_uniondiscord    = "Union-Discord %s",
        presence_mainmenu        = "Im Hauptmenü",
        presence_timetrial       = "Zeitrennen",
        presence_partyrace       = "Rennpark",
        presence_rankmatch       = "Weltrennen",
        presence_fest            = "Festival-Spiel",
        presence_legend          = "Legendenwettkampf",
        presence_wait            = "Wartet",
        presence_racing          = "%s mit %s",
        presence_car             = "Rast",
        presence_boat            = "Segelt",
        presence_plane           = "Fliegt",
        presence_racingranked    = "Gewertetes Rennen auf %s",
        presence_normalspeed     = "Normale Geschwindigkeit",
        presence_highspeed       = "Hohes Tempo!",
        presence_sonicspeed      = "Sonic Tempo!",
        presence_supersonicspeed = "Super-Sonic Tempo!",
        presence_lap             = "Runde %s/3",
        presence_1st             = "1.",
        presence_2nd             = "2.",
        presence_3rd             = "3.",
        presence_4th             = "4.",
        presence_5th             = "5.",
        presence_6th             = "6.",
        presence_7th             = "7.",
        presence_8th             = "8.",
        presence_9th             = "9.",
        presence_10th            = "10.",
        presence_11th            = "11.",
        presence_12th            = "12.",
    },

    -- Updated Translation for 0.2 release: red1fouad (05-10-2025)
    Es = {
        presence_menu_offline    = "Inactivo en el menú principal",
        presence_menu_online     = "Inactivo en una sala en línea",
        presence_inmenus         = "En menús",
        presence_jukebox         = "¡Poniendo vinilos y girando el sonido!",
        presence_courseselect    = "Seleccionando un circuito",
        presence_prixselect      = "Seleccionando un Gran Premio",
        presence_class           = "Seleccionando una clase de velocidad",
        presence_racerselect     = "Seleccionando un personaje y una máquina",
        presence_friendmatch     = "Partida con amigos",
        presence_paused          = "Juego en pausa",
        presence_garage          = "Personalizando una máquina",
        presence_finish          = "Carrera terminada",
        presence_uniondiscord    = "UnionDiscord %s",
        presence_mainmenu        = "Menú principal",
        presence_grandprix       = "Gran Premio",
        presence_timetrial       = "Contrarreloj",
        presence_partyrace       = "Parque de carreras",
        presence_rankmatch       = "Partida mundial",
        presence_fest            = "Partida de Festival",
        presence_legend          = "Competencia legendaria",
        presence_wait            = "Esperando",
        presence_racing          = "%s a %s",
        presence_car             = "Corriendo",
        presence_boat            = "Navegando",
        presence_plane           = "Volando",
        presence_racingranked    = "Compitiendo en %s rango",
        presence_normalspeed     = "a velocidad normal",
        presence_highspeed       = "a alta velocidad",
        presence_sonicspeed      = "a velocidad sónica",
        presence_supersonicspeed = "¡a velocidad super sónica!",
        presence_lap             = "Vuelta %s/3",
        presence_1st             = "1.º",
        presence_2nd             = "2.º",
        presence_3rd             = "3.º",
        presence_4th             = "4.º",
        presence_5th             = "5.º",
        presence_6th             = "6.º",
        presence_7th             = "7.º",
        presence_8th             = "8.º",
        presence_9th             = "9.º",
        presence_10th            = "10.º",
        presence_11th            = "11.º",
        presence_12th            = "12.º",
    },

    -- Updated Translation for 0.2 release: red1fouad (05-10-2025)
    EsUS = {
        presence_menu_offline    = "Inactivo en el menú principal",
        presence_menu_online     = "Inactivo en un lobby en línea",
        presence_inmenus         = "En menús",
        presence_jukebox         = "¡Tocando vinilos y girando el ritmo!",
        presence_courseselect    = "Seleccionando una pista",
        presence_prixselect      = "Seleccionando un Gran Premio",
        presence_class           = "Seleccionando una clase de velocidad",
        presence_racerselect     = "Seleccionando un personaje y una máquina",
        presence_friendmatch     = "Partida con amigos",
        presence_paused          = "Juego en pausa",
        presence_garage          = "Personalizando una máquina",
        presence_finish          = "Carrera terminada",
        presence_uniondiscord    = "UnionDiscord %s",
        presence_mainmenu        = "Menú principal",
        presence_grandprix       = "Gran Premio",
        presence_timetrial       = "Contrarreloj",
        presence_partyrace       = "Parque de carreras",
        presence_rankmatch       = "Partida mundial",
        presence_fest            = "Festival",
        presence_legend          = "Competencia legendaria",
        presence_wait            = "Esperando",
        presence_racing          = "Corriendo en %s",
        presence_racingranked    = "Compitiendo en %s rango",
        presence_normalspeed     = "a velocidad normal",
        presence_highspeed       = "a alta velocidad",
        presence_sonicspeed      = "a velocidad sónica",
        presence_supersonicspeed = "¡a velocidad super sónica!",
        presence_lap             = "Vuelta %s/3",
        presence_1st             = "1.º",
        presence_2nd             = "2.º",
        presence_3rd             = "3.º",
        presence_4th             = "4.º",
        presence_5th             = "5.º",
        presence_6th             = "6.º",
        presence_7th             = "7.º",
        presence_8th             = "8.º",
        presence_9th             = "9.º",
        presence_10th            = "10.º",
        presence_11th            = "11.º",
        presence_12th            = "12.º",
    },

    -- Machine Translation
    Ru = {
        presence_menu_offline   = "В главном меню бездействует",
        presence_menu_online    = "Бездействует в онлайн-лобби",
        presence_jukebox        = "Крутит пластинку и включает звук!",
        presence_courseselect   = "Выбор трассы",
        presence_grandprix      = "Выбор Гран-при",
        presence_class          = "Выбор класса скорости",
        presence_racerselect    = "Выбор персонажа и машины",
        presence_friendmatch    = "Игра с друзьями",
        presence_paused         = "Игра на паузе",
        presence_garage         = "Настройка машины",
        presence_finish         = "Гонка завершена",
        presence_uniondiscord   = "UnionDiscord %s",
    },

    -- Translated by DHedge for 2.0 release (05-10-2025)
    Pl = {
        presence_menu_offline = "Bezczynność w Menu Głównym",
        presence_menu_online  = "Bezczynność w Lobby Sieciowym",
        presence_inmenus      = "W Menu",
        presence_jukebox      = "Posłuchaj Muzyki!",
        presence_courseselect = "Wybieranie Toru",
        presence_prixselect   = "Wybieranie Grand Prix",
        presence_class        = "Wybieranie klasy prędkości",
        presence_racerselect  = "Wybieranie Postaci i Maszyny",
        presence_friendmatch  = "Mecz ze Znajomymi",
        presence_paused       = "Pauza Gry",
        presence_garage       = "Dostosowywanie Maszyny",
        presence_finish       = "Wyścig Zakończony",
        presence_uniondiscord = "UnionDiscord %s",
        presence_mainmenu     = "Menu Główne",
        presence_grandprix    = "Grand Prix",
        presence_timetrial    = "Próba Czasowa",
        presence_partyrace      = "Park Wyścigowy",
        presence_rankmatch      = "Mecz Światowy",
        presence_fest           = "Festiwal",
        presence_legend         = "Konkurencja Legendy",
        presence_wait           = "Czekanie",
        presence_racing         = "%s w %s",
        presence_car            = "Ściganie się",
        presence_boat            = "Pływanie",
        presence_plane           = "Latanie",
        presence_racingranked    = "Competing at %s Rank",
        presence_normalspeed     = "Normalnej Prędkości",
        presence_highspeed       = "Wysokiej Prędkości",
        presence_sonicspeed      = "Prędkości Sonicznej",
        presence_supersonicspeed = "Prędkości Super Sonicznej!",
        presence_lap             = "Okrążenie %s/3",
        presence_1st             = "1st",
        presence_2nd             = "2nd",
        presence_3rd             = "3rd",
        presence_4th             = "4th",
        presence_5th             = "5th",
        presence_6th             = "6th",
        presence_7th             = "7th",
        presence_8th             = "8th",
        presence_9th             = "9th",
        presence_10th            = "10th",
        presence_11th            = "11th",
        presence_12th            = "12th",
                
    },

    -- Updated translations for 0.21: limavi__ (06-10-2025)
    Pt = {
        presence_menu_offline    = "Inativo no Menu Principal",
        presence_menu_online     = "Inativo em um Saguão Online",
        presence_inmenus         = "Nos Menus",
        presence_jukebox         = "Ouvindo uma Música",
        presence_courseselect    = "Selecionando uma Pista",
        presence_prixselect      = "Selecionando um Grand Prix",
        presence_class           = "Selecionando uma Classe de Velocidade",
        presence_racerselect     = "Selecionando um Personagem e Veículo",
        presence_friendmatch     = "Partida com Amigos",
        presence_paused          = "Jogo Pausado",
        presence_garage          = "Customizando um Veículo",
        presence_finish          = "Corrida Finalizada",
        presence_uniondiscord    = "UnionDiscord %s",
        presence_mainmenu        = "Menu Principal",
        presence_grandprix       = "Grand Prix",
        presence_timetrial       = "Prova de Tempo",
        presence_partyrace       = "Parque de Corrida",
        presence_rankmatch       = "Partida Mundial",
        presence_fest            = "Festival",
        presence_legend          = "Competição Lenda",
        presence_wait            = "Aguardando",
        presence_racing          = "%s na %s",
        presence_car             = "Correndo",
        presence_boat            = "Navegando",
        presence_plane           = "Voando",
        presence_racingranked    = "Competindo em %s Rank",
        presence_normalspeed     = "Velocidade Normal",
        presence_highspeed       = "Velocidade Alta",
        presence_sonicspeed      = "Velocidade Sonic",
        presence_supersonicspeed = "Velocidade Super Sonic!",
        presence_lap             = "Volta %s/3",
        presence_1st             = "1st",
        presence_2nd             = "2nd",
        presence_3rd             = "3rd",
        presence_4th             = "4th",
        presence_5th             = "5th",
        presence_6th             = "6th",
        presence_7th             = "7th",
        presence_8th             = "8th",
        presence_9th             = "9th",
        presence_10th            = "10th",
        presence_11th            = "11th",
        presence_12th            = "12th",
    },


    -- Machine Translation
    Ko = {
        presence_menu_offline   = "메인 메뉴에서 대기 중",
        presence_menu_online    = "온라인 로비에서 대기 중",
        presence_jukebox        = "레코드를 돌리고 음악을 재생합니다!",
        presence_courseselect   = "코스 선택 중",
        presence_grandprix      = "그랑프리 선택 중",
        presence_class          = "속도 클래스를 선택 중",
        presence_racerselect    = "캐릭터와 머신 선택 중",
        presence_friendmatch    = "친구 매치",
        presence_paused         = "게임 일시 정지",
        presence_garage         = "머신 커스터마이즈 중",
        presence_finish         = "레이스 종료",
        presence_uniondiscord   = "UnionDiscord %s",
    },

    -- Machine Translation
    ZhHans = {
        presence_menu_offline   = "在主菜单中闲置",
        presence_menu_online    = "在在线大厅中闲置",
        presence_jukebox        = "放上唱片，播放音乐！",
        presence_courseselect   = "选择赛道",
        presence_grandprix      = "选择大奖赛",
        presence_class          = "选择速度等级",
        presence_racerselect    = "选择角色和赛车",
        presence_friendmatch    = "好友比赛",
        presence_paused         = "游戏已暂停",
        presence_garage         = "自定义赛车",
        presence_finish         = "比赛结束",
        presence_uniondiscord   = "UnionDiscord %s",
    },

    -- Machine Translation
    ZhHant = {
        presence_menu_offline   = "在主選單中閒置",
        presence_menu_online    = "在在線大廳中閒置",
        presence_jukebox        = "放上唱片，播放音樂！",
        presence_courseselect   = "選擇賽道",
        presence_grandprix      = "選擇大獎賽",
        presence_class          = "選擇速度等級",
        presence_racerselect    = "選擇角色和賽車",
        presence_friendmatch    = "好友比賽",
        presence_paused         = "遊戲已暫停",
        presence_garage         = "自定義賽車",
        presence_finish         = "比賽結束",
        presence_uniondiscord   = "UnionDiscord %s",
    },

    -- Machine Translation
    Th = {
        presence_menu_offline   = "ไม่ทำอะไรในเมนูหลัก",
        presence_menu_online    = "ไม่ทำอะไรในล็อบบี้ออนไลน์",
        presence_jukebox        = "ใส่แผ่นเสียงและเล่นเพลง!",
        presence_courseselect   = "เลือกสนามแข่ง",
        presence_grandprix      = "เลือกกรังด์ปรีซ์",
        presence_class          = "เลือกคลาสความเร็ว",
        presence_racerselect    = "เลือกตัวละครและเครื่อง",
        presence_friendmatch    = "แมทช์กับเพื่อน",
        presence_paused         = "เกมหยุดชั่วคราว",
        presence_garage         = "ปรับแต่งเครื่อง",
        presence_finish         = "การแข่งขันจบแล้ว",
        presence_uniondiscord   = "UnionDiscord %s",
    },
}

Localisation.GameModeMap = {
    None        = "presence_mainmenu",
    GrandPrix   = "presence_grandprix",
    PartyRace   = "presence_partyrace",
    TimeTrial   = "presence_timetrial",
    RankMatch   = "presence_rankmatch",
    FriendMatch = "presence_friendmatch",
    FriendMatch_NSW = "",
    Fest        = "presence_fest",
    Legend      = "presence_legend",
    Garage      = "presence_garage",
    Dev_FreeRun = "",
    Num         = "",
}

Localisation.SpeedClassMap = {
    NormalSpeed     = "presence_normalspeed",
    HighSpeed       = "presence_highspeed",
    SonicSpeed      = "presence_sonicspeed",
    SuperSonicSpeed = "presence_supersonicspeed",
}

Localisation.VehicleRacingMap = {
    VehicleTypeCar = "presence_car",
    VehicleTypeBoat = "presence_boat",
    VehicleTypePlane = "presence_plane",
}

function Localisation.GetVehicleDrivingText(vehicle_id)
    local key = Localisation.VehicleRacingMap[vehicle_id]
    if not key or key == "" then
        return "" -- fallback for unmapped modes
    end

    return Localisation.T(key)
end

function Localisation.GetGameModeText(mode_id)
    local key = Localisation.GameModeMap[mode_id]
    if not key or key == "" then
        return "" -- fallback for unmapped modes
    end

    return Localisation.T(key)
end

function Localisation.GetSpeedClassText(speed_id)
    local key = Localisation.SpeedClassMap[speed_id]
    if not key or key == "" then
        return "" -- fallback for unmapped modes
    end

    return Localisation.T(key)
end

local function T(key, ...)
    local loclibrary = StaticFindObject("/Script/UnionSystem.Default__LocalizationFunctionLibrary")
    local lang = Structures.GetLanguageAsEnumFromID(loclibrary:GetTextLang())
    
    -- Currently supported languages, thanks to Community Translations.
    local allowed_languages = {
        En = true,
        Fr = true,
        It = true,
        De = true,
        Es = true,
        EsUS = true,
        Pl = true,
        Pt = true,
    }
    
    -- If we're not using an enabled language, just default back to English.
    if not allowed_languages[lang] then
        lang = "En"
    end
    
    local entry = LocalisationKey[lang][key]

    if not entry then
        return key -- fallback to key if not found, this shouldn't happen except for test scenarios.
    end

    return string.format(entry, ...)
end

function Localisation.GetWaiting()
    return T("presence_wait")
end

Localisation.T = T

return Localisation
